### ISSUE TITLE
Notify of available OS updates and ask if they should be done

### ISSUE THREAD

**Issue by vRobM** [ArkEcosystem/core-commander#18]
Forcing updates every time gets in the way quickly when starting and restarting commander.

Removing that requirement makes sense, leaving the option to do it if needed, skipping otherwise.

Recent versions of Ubuntu already have a rolling status and background check for available updates which notifies you upon login.

Faster startup time is another benefit for commander, as well as avoiding typing in sudo passwords.

**Comment by reConNico** [comment]
That is already implemented or do I get your wrong?

![commander_ask](https://user-images.githubusercontent.com/15830979/41437503-eced6f6e-7024-11e8-96cc-ec7ac7a9b628.png)

**Comment by vRobM** [comment]
You are right it is.. but that should be the first thing a user sees.

Not immediately being asked for a sudo password every time.

**Comment by vRobM** [comment]
It should also not run apt update every time commander is run, the system does already.

**Comment by reConNico** [comment]
Many features of the script needs sudo access including the system updates that's why sudo is required to run the commander and it should be fine.

Experienced server engineers will keep an eye on the system updates by themselves and will not use the commander for it.

You're right but calling `sudo apt-get update` isn't wrong because after the system boot there could be a time difference to starting the commander.

**Comment by vRobM** [comment]
Every time the user logs in they will see if there are updates.

So instead of running 'sudo apt update' (apt-get is deprecated so it is kinda wrong); run:
/usr/lib/update-notifier/apt-check --human-readable  (which doesn't need sudo) and let the user decide with an option in Miscellaneous. 

Much better UX imho

**Comment by supaiku0** [comment]
This should be fixed with #35.
